name: blog publish

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout blog repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout pelican theme repo
        uses: actions/checkout@v3
        with:
          repository: albertodonato/pelican-chemistry
          path: pelican-chemistry
      - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
        env:
          PELICAN_THEME_FOLDER: pelican-chemistry
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
