name: blog publish

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout blog repo
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
        env:
          PELICAN_THEME_FOLDER: pelican-chemistry
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
