name: blog publish

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system -r requirements.txt
      - name: build blog
        run: |
          pelican content -o output -s publishconf.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
